// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: article.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
  title,
  content,
  updated_at,
  user_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, title, content, created_at, updated_at, user_id
`

type CreateArticleParams struct {
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	UpdatedAt time.Time `json:"updatedAt"`
	UserID    uuid.UUID `json:"userId"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Title,
		arg.Content,
		arg.UpdatedAt,
		arg.UserID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = $1
`

func (q *Queries) DeleteArticle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, id)
	return err
}

const getArticleById = `-- name: GetArticleById :one
SELECT a.id, a.title, a.content, a.created_at, a.updated_at, u.name as user_name, u.photo as user_photo FROM articles a
LEFT JOIN users u on u.id = a.user_id
WHERE a.id = $1 LIMIT 1
`

type GetArticleByIdRow struct {
	ID        uuid.UUID      `json:"id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	UserName  sql.NullString `json:"userName"`
	UserPhoto sql.NullString `json:"userPhoto"`
}

func (q *Queries) GetArticleById(ctx context.Context, id uuid.UUID) (GetArticleByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getArticleById, id)
	var i GetArticleByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserPhoto,
	)
	return i, err
}

const getArticleByUserId = `-- name: GetArticleByUserId :one
SELECT a.id, a.title, a.content, a.created_at, a.updated_at, u.name as user_name, u.photo as user_photo FROM articles a
LEFT JOIN users u on u.id = a.user_id
WHERE user_id = $1 LIMIT 1
`

type GetArticleByUserIdRow struct {
	ID        uuid.UUID      `json:"id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	UserName  sql.NullString `json:"userName"`
	UserPhoto sql.NullString `json:"userPhoto"`
}

func (q *Queries) GetArticleByUserId(ctx context.Context, userID uuid.UUID) (GetArticleByUserIdRow, error) {
	row := q.db.QueryRowContext(ctx, getArticleByUserId, userID)
	var i GetArticleByUserIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserPhoto,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT a.id, a.title, a.content, a.created_at, a.updated_at, u.name as user_name, u.photo as user_photo FROM articles a
LEFT JOIN users u on u.id = a.user_id
ORDER BY a.id
LIMIT $1
OFFSET $2
`

type ListArticlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListArticlesRow struct {
	ID        uuid.UUID      `json:"id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	UserName  sql.NullString `json:"userName"`
	UserPhoto sql.NullString `json:"userPhoto"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]ListArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticlesRow
	for rows.Next() {
		var i ListArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserPhoto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
set title = $2,
content = $3,
updated_at = $4
WHERE id = $1
RETURNING id, title, content, created_at, updated_at, user_id
`

type UpdateArticleParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	UpdatedAt time.Time `json:"updatedAt"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticle,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.UpdatedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
